TFG/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>RES-{000000}</displayFormat>
        <label>Re Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TFG/force-app/main/default/objects/Booking__c/fields/CheckIn__c.field-meta.xml
<CustomField>
    <fullName>CheckIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the check in has been done</description>
    <label>Check-In</label>
    <type>Checkbox</type>
</CustomField>

TFG/force-app/main/default/objects/Booking__c/fields/Guest__c.field-meta.xml
<CustomField>
    <fullName>Guest__c</fullName>
    <label>Guest</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

TFG/force-app/main/default/objects/Booking__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Stores a temporal UUID Allowing clients to see the page with all requests of its booking</description>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

TFG/force-app/main/default/objects/Case/fields/BookingId__c.field-meta.xml
<CustomField>
    <fullName>BookingId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Request</relationshipLabel>
    <relationshipName>Request</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

TFG/force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TFG/force-app/main/default/classes/ClientsPageController.cls
/**
 * @description       : Controller used in the Digital Experience web page that clients access via URL. We use without sharing because the guest user that clients use have no permissions for most of the functionallities done in this class.
 * @author            : Fernando Ibarra
 * @group             : 
 * @last modified on  : 03-04-2026
 * @last modified by  : Fernando Ibarra
**/
public without sharing class ClientsPageController {

    /**
    * @description Returns true if the given booking by its UUID Exist. If not, throw an exception
    * @author Fernando Ibarra | 03-04-2026 
    * @param bookingId UUID of the Booking
    * @return Boolean 
    **/
    @AuraEnabled
    public static Boolean validateBooking(String bookingId){
        Booking__c booking = [SELECT Id FROM Booking__c WHERE UUID__c =: bookingId];
        if(booking == null) throw new AuraHandledException('Ex');
        return true; 
    }

    /**
    * @description Obtains all the Requests linked to a specific booking. We use the UUID field to do this query.
    * @author Fernando Ibarra | 03-04-2026 
    * @param bookingId UUID of the Booking
    * @return List<Case> Requests linked to the Booking
    **/
    @AuraEnabled
    public static List<Case> getCasesInfo(String bookingId){
        if(String.isBlank(bookingId)) throw new AuraHandledException('Ex');
        return [SELECT Id, CaseNumber, Description, Subject, Status, Category__c, Priority, CreatedDate FROM Case WHERE BookingId__r.UUID__c =: bookingId AND BookingId__r.CheckIn__c = TRUE ORDER BY CreatedDate DESC];
    }


    
    /**
    * @description Obtains all the info of a specific Request via its Id
    * @author Fernando Ibarra | 03-04-2026 
    * @param caseId 
    * @return Case 
    **/
    @AuraEnabled
    public static Case getCaseInfo(Id caseId){
        return [SELECT Id, CaseNumber, Description, Subject, Status, Category__c, Priority, CreatedDate FROM Case WHERE Id =: caseId LIMIT 1];
    }

    /**
    * @description Create a new Request for a specific booking. 
    * @author Fernando Ibarra | 03-04-2026 
    * @param bookingId 
    * @return Case 
    **/
    @AuraEnabled
    public static Case createNewCase(String bookingId){
        Booking__c booking = [SELECT Id, Guest__c FROM Booking__c WHERE UUID__c =: bookingId ];
        Case newCase = new Case();
        newCase.BookingId__c = booking.Id;
        newCase.Status = 'New';
        newCase.Origin = 'Web';
        newCase.ContactId = booking.Guest__c;
        insert newCase;
        return getCaseInfo(newCase.Id);
    }


    /**
    * @description Obtains the picklist values of a specific field of the Request object
    * @author Fernando Ibarra | 03-04-2026 
    * @param fieldName 
    * @return List<Map<String, String>> 
    **/
    @AuraEnabled
    public static List<Map<String,String>> getPicklistValues(String fieldName){
        List<Map<String,String>> picklist = new List<Map<String,String>>();
        List<Schema.PicklistEntry> ple = Schema.getGlobalDescribe().get('Case').getDescribe().fields.getMap().get(fieldName).getDescribe().getPicklistValues() ;

        for (Schema.PicklistEntry entry : ple) {
            picklist.add( new Map<String, String>{ 'label' => entry.getLabel() , 'value' => entry.getValue()});
            
        }
        return picklist;
    }

    /**
    * @description Updates a single case
    * @author Fernando Ibarra | 03-04-2026 
    * @param caseToUpdate 
    **/
    @AuraEnabled
    public static void updateCase(Case caseToUpdate){
        update caseToUpdate;
    }

    /**
    * @description Moves a case to In Progress
    * @author Fernando Ibarra | 03-04-2026 
    * @param caseId 
    **/
    @AuraEnabled
    public static void moveCaseToInProgress(Id caseId){
        update new Case( Id = caseId, Status = 'InProgress');
    }

}